insert into user_tb(email, name, password, role) values('tngus@naver.com', '김수현', '$2a$12$w0VeGEJ7Cj7YE/PU9EHmAOSJsnnTXkOGZi3QE6W4.gJUB5EIVbiDW', 'ROLE_STUDENT');
insert into user_tb(email, name, password, role) values('soso@naver.com', '박소현', '$2a$12$AFOtb0QbI6BcLVTLaiYpuOnBlMDg5jTfGRez9miMYwC0wFCbbXT6q', 'ROLE_STUDENT');
insert into user_tb(email, name, password, role) values('gihae@naver.com', '김기해', '$2a$12$0ucbDurCSFuguHpqbQLF9u6BZJKc1IsYf4pR5OUPka2SDHie9MyQe', 'ROLE_STUDENT');
insert into user_tb(email, name, password, role) values('gihae2@naver.com', '김기해2', '$2a$12$0ucbDurCSFuguHpqbQLF9u6BZJKc1IsYf4pR5OUPka2SDHie9MyQe', 'ROLE_INSTRUCTOR');

insert into course_tb(name, description) values('자료구조 059', '2-2');
insert into course_tb(name, description) values('자료구조 060', '2-2');
insert into course_tb(name, description) values('C언어', '1-2');
insert into course_tb(name, description) values('C++', '2-1');
insert into course_tb(name, description) values('파이썬', '1-1');
insert into course_tb(name, description) values('자바', '2-2');
insert into course_tb(name, description) values('알고리즘', '3-1');
insert into course_tb(name, description) values('DB', '3-2');
insert into course_tb(name, description) values('사물인터넷', '4-2');

--insert into vm_tb(user_id, vmname, course_id, port, scope, control, state) values(2, '알고리즘', 1, 6085, 1, 1, 'stop');
--insert into vm_tb(user_id, vmname, course_id, port, scope, control, state) values(2, '자료구조', 1, 6086, 0, 1, 'stop');
--insert into vm_tb(user_id, vmname, course_id, port, scope, control, state) values(3, '알고리즘', 1, 6087, 1, 1, 'stop');
--insert into vm_tb(user_id, vmname, course_id, port, scope, control, state) values(3, '자료구조', 1, 6088, 0, 1, 'stop');

insert into course_user_tb(user_id, course_id, accept) values(1, 1, true);
insert into course_user_tb(user_id, course_id, accept) values(2, 1, true);
insert into course_user_tb(user_id, course_id, accept) values(3, 1, true);

insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글1', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글2', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글3', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글4', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글5', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글6', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글7', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글8', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글9', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글10', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글11', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글12', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글13', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글14', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글15', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글16', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글17', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글18', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글19', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글20', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글21', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글22', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글23', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글24', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글25', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글26', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글27', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글28', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글29', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글30', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글31', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글32', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글33', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글34', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글35', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글36', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글37', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글38', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글39', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글40', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글41', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글42', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글43', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글44', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글45', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글46', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글47', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글48', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글49', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글50', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글51', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글52', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글53', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글54', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글55', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글56', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글57', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글58', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글59', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('공지글60', 'gh', '공지 글이지롱!><', true, 'NOTICE', 1, 3);

insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글1', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글2', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글3', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글4', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글5', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글6', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글7', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글8', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글9', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글10', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글11', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글12', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글13', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글14', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글15', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글16', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글17', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글18', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글19', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글20', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글21', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글22', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글23', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글24', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글25', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글26', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글27', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글28', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글29', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('질문글30', 'gh', '질문 글이지롱!><', true, 'QUESTION', 1, 3);

insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글1', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글2', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글3', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글4', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글5', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글6', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글7', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글8', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글9', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글10', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글11', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글12', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글13', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글14', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글15', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글16', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글17', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글18', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글19', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글20', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글21', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글22', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글23', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글24', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글25', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글26', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글27', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글28', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글29', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글30', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글31', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글32', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글33', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글34', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글35', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글36', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글37', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글38', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글39', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글40', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글41', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글42', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글43', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글44', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글45', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글46', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글47', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글48', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글49', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);
insert into post_tb(title, author, content, open, category, course_id, user_id) values('자유글50', 'gh', '자유 글이지롱!><', true, 'FREE', 1, 3);

insert into reply_tb(content, author, ref, ref_order, step, parent_num, answer_num, user_id, post_id) values('댓글1', 'ㄱㅎ', 0, 0, 0, 0, 0, 4, 1);

